import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import tensorflow as tf
from sklearn.metrics import confusion_matrix




def split_date_column(df: pd.DataFrame) -> pd.DataFrame:
    """
    Splits the 'Date' column in a pandas DataFrame into separate date components.

    The input DataFrame must contain a column named 'Date'.
    The 'Date' column should be in a datetime-compatible format.
    """
    df = df.copy()
    df["Date"] = pd.to_datetime(df["Date"])
    df["Year"] = df["Date"].dt.year
    df["Month"] = df["Date"].dt.month
    df["Day"] = df["Date"].dt.day
    df["WeekOfYear"] = df.Date.dt.isocalendar().week
    return df





def plot_loss_curves(history):
    """
    Plot training & validation loss and metrics from a Keras History object.
    """

    loss = history.history.get("loss")
    val_loss = history.history.get("val_loss")

    # Handle accuracy naming differences
    acc = history.history.get("accuracy") or history.history.get("acc")
    val_acc = history.history.get("val_accuracy") or history.history.get("val_acc")

    epochs = range(1, len(loss) + 1)

    fig, ax = plt.subplots(1, 2, figsize=(12, 4))

    # ---- Loss plot ----
    ax[0].plot(epochs, loss, label="Training Loss")
    if val_loss is not None:
        ax[0].plot(epochs, val_loss, label="Validation Loss")
    ax[0].set_title("Loss")
    ax[0].set_xlabel("Epochs")
    ax[0].set_ylabel("Loss")
    ax[0].legend()
    ax[0].grid(True)

    # ---- Accuracy plot ----
    if acc is not None:
        ax[1].plot(epochs, acc, label="Training Accuracy")
    if val_acc is not None:
        ax[1].plot(epochs, val_acc, label="Validation Accuracy")
    ax[1].set_title("Accuracy")
    ax[1].set_xlabel("Epochs")
    ax[1].set_ylabel("Accuracy")
    ax[1].legend()
    ax[1].grid(True)

    plt.tight_layout()



    

def plot_confusion_matrix(y_test, y_pred, model):
    """
    Plots a confusion matrix with both raw counts and normalized percentages.

    This function is designed for iterative use when evaluating multiple
    classification models. By passing different model names, it allows
    easy visual comparison of model performance.

    Parameters
    ----------
    y_test : array-like
        True class labels from the test dataset.

    y_pred : array-like
        Predicted class labels generated by the model.

    model : str
        Name of the model (e.g., 'Logistic Regression', 'Random Forest').
        This is displayed in the plot title for easy identification
        when comparing multiple models.

    Returns
    -------
    None
        Displays the confusion matrix plot.
    """

    # Set plot style
    sns.set_theme(style="white")
    figsize = (10, 10)

    # Compute confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Normalize confusion matrix by row (true labels)
    cm_norm = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis]
    n_classes = cm.shape[0]

    # Create figure and axis
    fig, ax = plt.subplots(figsize=figsize)

    # Display confusion matrix
    cax = ax.matshow(cm, cmap=plt.cm.Blues)
    fig.colorbar(cax)

    # Class labels (default: numeric)
    labels = np.arange(n_classes)

    # Axis labels and title
    ax.set(
        title=f"Confusion Matrix - {model}",
        xlabel="Predicted Label",
        ylabel="True Label",
        xticks=np.arange(n_classes),
        yticks=np.arange(n_classes),
        xticklabels=labels,
        yticklabels=labels
    )

    # Move x-axis label to bottom
    ax.xaxis.set_label_position("bottom")
    ax.xaxis.tick_bottom()

    # Font sizes
    ax.yaxis.label.set_size(20)
    ax.xaxis.label.set_size(20)
    ax.title.set_size(20)

    # Threshold for text color contrast
    threshold = (cm.max() + cm.min()) / 2

    # Add counts and percentages to each cell
    for i, j in itertools.product(range(n_classes), range(n_classes)):
        ax.text(
            j,
            i,
            f"{cm[i, j]} ({cm_norm[i, j]*100:.1f}%)",
            ha="center",
            va="center",
            color="white" if cm[i, j] > threshold else "black",
            size=15
        )

    plt.show()
