import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import tensorflow as tf
import joblib
import tensorflow_probability as tfp
from pathlib import Path 
from sklearn.metrics import confusion_matrix

# ///////////////////////////////////////////////////////////////////////////////////////////////////

def split_date_column(df: pd.DataFrame) -> pd.DataFrame:
    """
    Splits the 'Date' column in a pandas DataFrame into separate date components.

    The input DataFrame must contain a column named 'Date'.
    The 'Date' column should be in a datetime-compatible format.
    """
    df = df.copy()
    df["Date"] = pd.to_datetime(df["Date"])
    df["Year"] = df["Date"].dt.year
    df["Month"] = df["Date"].dt.month
    df["Day"] = df["Date"].dt.day
    df["WeekOfYear"] = df.Date.dt.isocalendar().week
    return df 

# ///////////////////////////////////////////////////////////////////////////////////////////////////

def plot_loss_curves(history):
    """
    Plot training & validation loss and metrics from a Keras History object.
    """

    loss = history.history.get("loss")
    val_loss = history.history.get("val_loss")

    # Handle accuracy naming differences
    acc = history.history.get("accuracy") or history.history.get("acc")
    val_acc = history.history.get("val_accuracy") or history.history.get("val_acc")

    epochs = range(1, len(loss) + 1)

    fig, ax = plt.subplots(1, 2, figsize=(12, 4))

    # ---- Loss plot ----
    ax[0].plot(epochs, loss, label="Training Loss")
    if val_loss is not None:
        ax[0].plot(epochs, val_loss, label="Validation Loss")
    ax[0].set_title("Loss")
    ax[0].set_xlabel("Epochs")
    ax[0].set_ylabel("Loss")
    ax[0].legend()
    ax[0].grid(True)

    # ---- Accuracy plot ----
    if acc is not None:
        ax[1].plot(epochs, acc, label="Training Accuracy")
    if val_acc is not None:
        ax[1].plot(epochs, val_acc, label="Validation Accuracy")
    ax[1].set_title("Accuracy")
    ax[1].set_xlabel("Epochs")
    ax[1].set_ylabel("Accuracy")
    ax[1].legend()
    ax[1].grid(True)

    plt.tight_layout()

# ///////////////////////////////////////////////////////////////////////////////////////////////////

def plot_confusion_matrix(y_test, y_pred, model):
    """
    Plots a confusion matrix with both raw counts and normalized percentages.

    This function is designed for iterative use when evaluating multiple
    classification models. By passing different model names, it allows
    easy visual comparison of model performance.

    Parameters
    ----------
    y_test : array-like
        True class labels from the test dataset.

    y_pred : array-like
        Predicted class labels generated by the model.

    model : str
        Name of the model (e.g., 'Logistic Regression', 'Random Forest').
        This is displayed in the plot title for easy identification
        when comparing multiple models.

    Returns
    -------
    None
        Displays the confusion matrix plot.
    """

    # Set plot style
    sns.set_theme(style="white")
    figsize = (10, 10)

    # Compute confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Normalize confusion matrix by row (true labels)
    cm_norm = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis]
    n_classes = cm.shape[0]

    # Create figure and axis
    fig, ax = plt.subplots(figsize=figsize)

    # Display confusion matrix
    cax = ax.matshow(cm, cmap=plt.cm.Blues)
    fig.colorbar(cax)

    # Class labels (default: numeric)
    labels = np.arange(n_classes)

    # Axis labels and title
    ax.set(
        title=f"Confusion Matrix - {model}",
        xlabel="Predicted Label",
        ylabel="True Label",
        xticks=np.arange(n_classes),
        yticks=np.arange(n_classes),
        xticklabels=labels,
        yticklabels=labels
    )

    # Move x-axis label to bottom
    ax.xaxis.set_label_position("bottom")
    ax.xaxis.tick_bottom()

    # Font sizes
    ax.yaxis.label.set_size(20)
    ax.xaxis.label.set_size(20)
    ax.title.set_size(20)

    # Threshold for text color contrast
    threshold = (cm.max() + cm.min()) / 2

    # Add counts and percentages to each cell
    for i, j in itertools.product(range(n_classes), range(n_classes)):
        ax.text(
            j,
            i,
            f"{cm[i, j]} ({cm_norm[i, j]*100:.1f}%)",
            ha="center",
            va="center",
            color="white" if cm[i, j] > threshold else "black",
            size=15
        )

    plt.show()

# ///////////////////////////////////////////////////////////////////////////////////////////////////

def save_model(model, path): 
    """Save a fitted model to disk.""" 
    path = Path(path) 
    path.parent.mkdir(parents=True, exist_ok=True) 
    joblib.dump(model, path) 
    print(f"Model saved to: {path}")

# ///////////////////////////////////////////////////////////////////////////////////////////////////

def box(lam, im_size):
    """
    Generate a random bounding box for CutMix.

    The bounding-box area is approximately determined by `lam`:
        box_area / image_area ~= 1 - lam

    Args:
        lam: Scalar lambda sampled from a Beta distribution.
        im_size: Height and width of the square image.

    Returns:
        y1: Top coordinate of the bounding box.
        x1: Left coordinate of the bounding box.
        box_h: Height of the bounding box.
        box_w: Width of the bounding box.
    """
    # Calculate the side length of the CutMix region.
    cut_ratio = tf.sqrt(1.0 - lam)

    box_w = tf.cast(im_size * cut_ratio, tf.int32)
    box_h = tf.cast(im_size * cut_ratio, tf.int32)

    # Randomly select the center of the bounding box.
    cx = tf.random.uniform(
        shape=(),
        minval=0,
        maxval=im_size,
        dtype=tf.int32,
    )

    cy = tf.random.uniform(
        shape=(),
        minval=0,
        maxval=im_size,
        dtype=tf.int32,
    )

    # Calculate bounding-box coordinates.
    x1 = cx - box_w // 2
    y1 = cy - box_h // 2

    x2 = cx + box_w // 2
    y2 = cy + box_h // 2

    # Clip the box so that it stays inside the image.
    x1 = tf.clip_by_value(x1, 0, im_size)
    y1 = tf.clip_by_value(y1, 0, im_size)

    x2 = tf.clip_by_value(x2, 0, im_size)
    y2 = tf.clip_by_value(y2, 0, im_size)

    # Recalculate dimensions after clipping.
    box_w = tf.maximum(x2 - x1, 1)
    box_h = tf.maximum(y2 - y1, 1)

    return y1, x1, box_h, box_w

# ///////////////////////////////////////////////////////////////////////////////////////////////////

def cutmix(
    train_dataset_1,
    train_dataset_2,
    im_size,
    alpha=0.2,
):
    """
    Apply CutMix augmentation to two image-label pairs.

    CutMix replaces a randomly selected rectangular region of image 1
    with the corresponding region from image 2. The labels are mixed
    according to the proportion of each image present in the final image.

    Args:
        train_dataset_1: Tuple of (image_1, label_1).
        train_dataset_2: Tuple of (image_2, label_2).
        im_size: Height and width of the square input images.
        alpha: Beta distribution parameter used to sample CutMix lambda.

    Returns:
        image: CutMix-augmented image.
        label: Mixed label.
    """
    (image_1, label_1), (image_2, label_2) = (
        train_dataset_1,
        train_dataset_2,
    )

    # Sample lambda from a Beta distribution.
    lam = tfp.distributions.Beta(alpha, alpha).sample()

    # Get the CutMix bounding box.
    r_y, r_x, r_h, r_w = box(lam, im_size)

    # Extract the corresponding region from image 2.
    crop_2 = tf.image.crop_to_bounding_box(
        image_2,
        r_y,
        r_x,
        r_h,
        r_w,
    )

    # Place image 2's crop at the same location in a blank image.
    pad_2 = tf.image.pad_to_bounding_box(
        crop_2,
        r_y,
        r_x,
        im_size,
        im_size,
    )

    # Extract the same region from image 1.
    crop_1 = tf.image.crop_to_bounding_box(
        image_1,
        r_y,
        r_x,
        r_h,
        r_w,
    )

    # Place image 1's crop at the same location.
    pad_1 = tf.image.pad_to_bounding_box(
        crop_1,
        r_y,
        r_x,
        im_size,
        im_size,
    )

    # Replace image 1's region with image 2's region.
    image = image_1 - pad_1 + pad_2

    # Recalculate lambda using the actual bounding-box area.
    box_area = tf.cast(r_h * r_w, tf.float32)
    total_area = tf.cast(im_size * im_size, tf.float32)

    lam = 1.0 - (box_area / total_area)

    # Mix the labels according to the area of each image.
    label = lam * label_1 + (1.0 - lam) * label_2

    return image, label 